"""Project-level .conversus/ directory management.

Handles creation, reading, and updating of the ``.conversus/`` directory
convention for conversus projects.  This directory contains:

- ``settings.json`` — provider defaults, model preferences
- ``output/`` — deliberation output (gitignored)
- Runtime-specific config dirs for permission grants

Each AI runtime has its own config convention:
- Claude Code → ``.claude/settings.json``
- OpenCode → ``.opencode/config.toml``
- GitHub Copilot → ``.github/copilot-settings.json``
- Gemini → ``.gemini/settings.json``
- Codex → ``.codex/settings.json``

``conversus init`` creates the ``.conversus/`` dir plus the runtime-specific
config files for whichever providers the user specifies.  After init, agents
using those runtimes run without interactive permission prompts.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Directory structure
# ---------------------------------------------------------------------------

CONVERSUS_DIR = ".conversus"
SETTINGS_FILE = "settings.json"
GITIGNORE_FILE = ".gitignore"

GITIGNORE_CONTENT = """\
# Conversus deliberation output
output/

# Session artifacts
*.log
*.tmp
"""

DEFAULT_SETTINGS: dict[str, Any] = {
    "default_provider": "claude-code",
    "default_model": "sonnet",
    "output_dir": "output",
    "runtimes": [],
}


# ---------------------------------------------------------------------------
# Runtime config generators
# ---------------------------------------------------------------------------

#: Safe permissions for conversus deliberation agents.
#: Read specs, write reviews, run safe commands. No destructive ops.
_SAFE_BASH_PERMS = [
    "Bash(cat:*)", "Bash(head:*)", "Bash(tail:*)", "Bash(wc:*)",
    "Bash(find:*)", "Bash(ls:*)", "Bash(diff:*)", "Bash(sort:*)",
    "Bash(echo:*)", "Bash(mkdir:*)", "Bash(pwd)", "Bash(which:*)",
    "Bash(git:*)", "Bash(python:*)", "Bash(python3:*)",
]

_FILE_PERMS = ["Read", "Write", "Edit", "Glob", "Grep", "Agent"]


def _claude_config() -> tuple[str, str, str | None]:
    """Return (dir_path, filename, content_or_None) for Claude Code config.

    Returns ``None`` as content to signal the caller to use
    :func:`_merge_claude_settings` instead of overwriting.
    """
    return ".claude", "settings.json", None


def _merge_claude_settings(project_root: Path, force: bool = False) -> Path | None:
    """Merge conversus agent permissions into existing .claude/settings.json.

    If the file exists, adds missing permissions without removing existing
    ones.  If the file doesn't exist, creates it with the minimal agent set.
    Returns the path if modified, None if unchanged.
    """
    claude_dir = project_root / ".claude"
    claude_dir.mkdir(exist_ok=True)
    settings_path = claude_dir / "settings.json"

    required_perms = set(_FILE_PERMS + _SAFE_BASH_PERMS)

    if settings_path.exists():
        try:
            existing = json.loads(settings_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            existing = {}

        current_allow = set(existing.get("permissions", {}).get("allow", []))
        missing = required_perms - current_allow
        if not missing and not force:
            return None  # Already has all needed permissions

        if not missing:
            return None  # Force doesn't matter if nothing to add

        # Merge: add missing permissions, preserve everything else
        merged_allow = list(current_allow | required_perms)
        existing.setdefault("permissions", {})["allow"] = sorted(merged_allow)
        settings_path.write_text(
            json.dumps(existing, indent=2) + "\n", encoding="utf-8",
        )
        return settings_path

    # New file — create with minimal agent permission set
    settings = {
        "permissions": {
            "allow": sorted(required_perms),
            "deny": [],
        },
    }
    settings_path.write_text(
        json.dumps(settings, indent=2) + "\n", encoding="utf-8",
    )
    return settings_path


def _opencode_config() -> tuple[str, str, str]:
    """Return (dir_path, filename, content) for OpenCode config."""
    # OpenCode uses TOML config
    content = """\
# OpenCode config for conversus agent execution
# Auto-generated by `conversus init`

[agent]
auto_approve = true
max_turns = 50

[model]
# Override per-task via conversus.yml agent.model field
"""
    return ".opencode", "config.toml", content


def _copilot_config() -> tuple[str, str, str]:
    """Return (dir_path, filename, content) for GitHub Copilot config."""
    settings = {
        "copilot": {
            "conversus_agent_mode": True,
            "auto_approve": True,
        },
    }
    return ".github", "copilot-settings.json", json.dumps(settings, indent=2) + "\n"


def _gemini_config() -> tuple[str, str, str]:
    """Return (dir_path, filename, content) for Gemini CLI config."""
    settings = {
        "sandbox": "none",
        "auto_approve": True,
        "conversus_agent": True,
    }
    return ".gemini", "settings.json", json.dumps(settings, indent=2) + "\n"


def _codex_config() -> tuple[str, str, str]:
    """Return (dir_path, filename, content) for Codex CLI config."""
    settings = {
        "full_auto": True,
        "quiet": True,
        "conversus_agent": True,
    }
    return ".codex", "settings.json", json.dumps(settings, indent=2) + "\n"


def _aider_config() -> tuple[str, str, str]:
    """Return (dir_path, filename, content) for Aider config."""
    content = """\
# Aider config for conversus agent execution
# Auto-generated by `conversus init`
auto-commits: false
auto-lint: false
yes-always: true
stream: false
"""
    return "", ".aider.conf.yml", content


#: Maps provider names to their config generator functions.
RUNTIME_CONFIGS: dict[str, Any] = {
    "claude-code": _claude_config,
    "opencode": _opencode_config,
    "copilot": _copilot_config,
    "gemini": _gemini_config,
    "codex": _codex_config,
    "aider": _aider_config,
}

#: All runtime names that have config generators.
AVAILABLE_RUNTIMES = sorted(RUNTIME_CONFIGS.keys())


# ---------------------------------------------------------------------------
# Init
# ---------------------------------------------------------------------------


def init_project(
    project_root: Path,
    *,
    runtimes: list[str] | None = None,
    default_provider: str = "claude-code",
    default_model: str = "sonnet",
    force: bool = False,
) -> dict[str, Path]:
    """Initialize a ``.conversus/`` directory and runtime configs.

    Creates the directory structure, settings files, and runtime-specific
    permission grants.  Idempotent — re-running updates settings without
    destroying existing output.

    Args:
        project_root: The project directory.
        runtimes: List of runtime names to configure (e.g.,
            ``["claude-code", "opencode"]``).  Defaults to
            ``["claude-code"]`` if not specified.
        default_provider: Default execution provider name.
        default_model: Default model identifier.
        force: If True, overwrite existing settings files.

    Returns:
        Dict of created/updated file paths keyed by description.
    """
    if runtimes is None:
        runtimes = ["claude-code"]

    conversus_dir = project_root / CONVERSUS_DIR
    output_dir = conversus_dir / "output"

    # Create .conversus/ and output/
    conversus_dir.mkdir(exist_ok=True)
    output_dir.mkdir(exist_ok=True)

    created: dict[str, Path] = {}

    # Write .conversus/settings.json
    settings_path = conversus_dir / SETTINGS_FILE
    if not settings_path.exists() or force:
        settings = {
            **DEFAULT_SETTINGS,
            "default_provider": default_provider,
            "default_model": default_model,
            "runtimes": runtimes,
        }
        settings_path.write_text(
            json.dumps(settings, indent=2) + "\n",
            encoding="utf-8",
        )
        created["settings"] = settings_path

    # Write .conversus/.gitignore
    gitignore_path = conversus_dir / GITIGNORE_FILE
    if not gitignore_path.exists() or force:
        gitignore_path.write_text(GITIGNORE_CONTENT, encoding="utf-8")
        created["gitignore"] = gitignore_path

    # Generate runtime-specific configs
    for runtime in runtimes:
        # Special case: claude-code uses merge semantics to preserve
        # existing .claude/settings.json permissions and hooks.
        if runtime == "claude-code":
            result = _merge_claude_settings(project_root, force=force)
            if result is not None:
                created["runtime:claude-code"] = result
            continue

        config_fn = RUNTIME_CONFIGS.get(runtime)
        if config_fn is None:
            continue

        dir_name, filename, content = config_fn()

        if dir_name:
            config_dir = project_root / dir_name
            config_dir.mkdir(exist_ok=True)
            config_path = config_dir / filename
        else:
            # Files that go in project root (e.g., .aider.conf.yml)
            config_path = project_root / filename

        if not config_path.exists() or force:
            config_path.write_text(content, encoding="utf-8")
            created[f"runtime:{runtime}"] = config_path

    return created


def read_settings(project_root: Path) -> dict[str, Any]:
    """Read ``.conversus/settings.json`` from the project root.

    Returns default settings if the file doesn't exist.
    """
    settings_path = project_root / CONVERSUS_DIR / SETTINGS_FILE
    if not settings_path.exists():
        return dict(DEFAULT_SETTINGS)
    try:
        return json.loads(settings_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return dict(DEFAULT_SETTINGS)


def find_conversus_dir(start: Path) -> Path | None:
    """Walk up from *start* to find a ``.conversus/`` directory.

    Returns the ``.conversus/`` path if found, or ``None``.
    """
    current = start.resolve()
    while current != current.parent:
        candidate = current / CONVERSUS_DIR
        if candidate.is_dir():
            return candidate
        current = current.parent
    return None
