"""Pure projection functions — take a capability iterable, return surface artifacts.

No file I/O happens here. The functions in this module are deterministic,
side-effect free, and take an explicit ``capabilities`` iterable so that
tests can project a synthetic registry without depending on the contents
of the real ``capabilities.py``.

The orchestrator at ``scripts/build-surfaces.py`` imports these functions,
wires them to the real registry, and handles writing the output files
(including the special case of patching only ``tools[]`` in the MCPB
manifest rather than overwriting the whole JSON).

Projection contract per surface:

==================================================  ================================================
Function                                            Return type
==================================================  ================================================
``project_to_cli(caps)``                            ``str`` — full ``engine/cli/__init__.py`` source
``project_to_mcp(caps)``                            ``str`` — full ``mcp_server.py`` source
``project_to_plugin_skills(caps)``                  ``dict[str, str]`` — ``{skill_name: SKILL.md text}``
``project_to_mcpb_manifest_tools(caps)``            ``list[dict]`` — value for the ``tools`` field
==================================================  ================================================
"""

from __future__ import annotations

from typing import Iterable

from conversus.registry.adapters import (
    DefaultCLIAdapter,
    DefaultMCPAdapter,
    DefaultMCPBAdapter,
    DefaultPluginAdapter,
)
from conversus.registry.adapters.mcpb import MCPBToolEntry
from conversus.registry.capability import Capability
from conversus.registry.params import Surface


# ---------------------------------------------------------------------------
# CLI projection
# ---------------------------------------------------------------------------


def project_to_cli(capabilities: Iterable[Capability]) -> str:
    """Render a full ``engine/cli/__init__.py`` source string.

    Preamble (``from __future__``, imports, ``@click.group``) plus one
    Click command block per CLI-opted capability, in registration order.
    """
    parts: list[str] = [_cli_preamble()]
    for cap in capabilities:
        if Surface.CLI not in cap.surfaces:
            continue
        adapter = cap.cli_adapter or DefaultCLIAdapter()
        parts.append(adapter.render(cap))
    return "\n\n\n".join(parts) + "\n"


def _cli_preamble() -> str:
    return (
        '"""Generated by scripts/build-surfaces.py — DO NOT EDIT.\n\n'
        "Source of truth: capabilities.py + conversus/registry/.\n"
        "Regenerate with: make build-surfaces\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "from pathlib import Path\n\n"
        "import click\n\n\n"
        '@click.group(name="conversus", help="Multi-agent deliberation engine.")\n'
        "def cli() -> None:\n"
        '    """Conversus CLI entry point."""'
    )


# ---------------------------------------------------------------------------
# MCP projection
# ---------------------------------------------------------------------------


def project_to_mcp(capabilities: Iterable[Capability]) -> str:
    """Render a full ``mcp_server.py`` source string.

    Preamble + one ``@mcp.tool()`` function per MCP-opted capability +
    stdio entry point. The runtime helper functions the existing
    hand-written server uses (``_decide``, ``_run_config``, etc.) live in
    handler modules and are imported lazily inside each generated tool.
    """
    parts: list[str] = [_mcp_preamble()]
    for cap in capabilities:
        if Surface.MCP not in cap.surfaces:
            continue
        adapter = cap.mcp_adapter or DefaultMCPAdapter()
        parts.append(adapter.render(cap))
    parts.append(_mcp_entry_point())
    return "\n\n\n".join(parts) + "\n"


def _mcp_preamble() -> str:
    return (
        '"""Generated by scripts/build-surfaces.py — DO NOT EDIT.\n\n'
        "Source of truth: capabilities.py + conversus/registry/.\n"
        "Regenerate with: make build-surfaces\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "from mcp.server.fastmcp import FastMCP\n\n"
        'mcp = FastMCP("conversus")'
    )


def _mcp_entry_point() -> str:
    return (
        'if __name__ == "__main__":\n'
        '    mcp.run(transport="stdio")'
    )


# ---------------------------------------------------------------------------
# Plugin (SKILL.md) projection
# ---------------------------------------------------------------------------


def project_to_plugin_skills(
    capabilities: Iterable[Capability],
) -> dict[str, str]:
    """Render every plugin-opted capability to its SKILL.md file text.

    Returns a mapping ``{skill_name: file_content}`` so the orchestrator
    can write each to ``claude-code-plugin/skills/<name>/SKILL.md``.
    """
    result: dict[str, str] = {}
    for cap in capabilities:
        if Surface.PLUGIN not in cap.surfaces:
            continue
        adapter = cap.plugin_adapter or DefaultPluginAdapter()
        result[cap.name] = adapter.render(cap)
    return result


# ---------------------------------------------------------------------------
# MCPB manifest tools[] projection
# ---------------------------------------------------------------------------


def project_to_mcpb_manifest_tools(
    capabilities: Iterable[Capability],
) -> list[MCPBToolEntry]:
    """Render the MCPB ``tools[]`` array for ``desktop-extension/manifest.json``.

    The orchestrator loads the existing manifest, replaces only this
    field, and writes the whole manifest back — so ``display_name``,
    ``long_description``, ``server`` config, ``user_config`` etc. survive
    regeneration untouched.
    """
    entries: list[MCPBToolEntry] = []
    for cap in capabilities:
        if Surface.MCPB not in cap.surfaces:
            continue
        adapter = cap.mcpb_adapter or DefaultMCPBAdapter()
        entries.append(adapter.render(cap))
    return entries
